GET http://localhost:8000/api/places HTTP/1.1

###

GET http://localhost:8000/api/place/11 HTTP/1.1

###

POST http://localhost:8000/api/auth/obtainToken HTTP/1.1
content-type: application/json

{
    "username": "john",
    "password": "password"
}

###

GET http://localhost:8000/api/auth/getUser HTTP/1.1
Authorization: Token 360de67e402560fe0e1fe5b85a83dd4f3c1b0174

###

POST http://localhost:8000/api/auth/register HTTP/1.1
content-type: application/json

{
    "username": "joedoee",
    "password": "password",
    "email": "some@email.com",
    "first_name": "Joe",
    "last_name": "Doe"
}

###
GET http://localhost:8000/api/packages HTTP/1.1
Authorization: Token 360de67e402560fe0e1fe5b85a83dd4f3c1b0174

###
GET http://localhost:8000/api/deletePackage/4 HTTP/1.1
Authorization: Token 360de67e402560fe0e1fe5b85a83dd4f3c1b0174


###
POST http://localhost:8000/api/createPackage
Authorization: Token 360de67e402560fe0e1fe5b85a83dd4f3c1b0174
Content-Type: application/json

{
    "starting_date": "2021-06-10",
    "no_of_days": "2",
    "no_of_people": "2",
    "price": "50000",
    "place_id": "9"
}
