# Generated by Django 3.2.3 on 2021-06-08 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='starting_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
