# Generated by Django 3.2.3 on 2021-06-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_package_starting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='destination',
            field=models.CharField(max_length=100),
        ),
    ]
